---
# Ensure directories are established as required
- include: directories.yml

- include: "setup-{{ ansible_os_family }}.yml"

- name: download automysqlbackup
  unarchive:
    src: "{{ automysqlbackup_download_url }}"
    dest: /tmp
    creates: /usr/local/bin/automysqlbackup
    remote_src: true
  register: installed
  tags:
    - automysqlbackup

- name: install postfix
  shell: debconf-set-selections <<< "postfix postfix/mailname string your.hostname.com" && debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'" && apt-get install --assume-yes postfix

- name: Install automysqlbackup
  package:
    name: automysqlbackup
    state: present
  when: installed.changed
  tags:
    - automysqlbackup

- name: set permissions
  file:
    path: /usr/local/bin/automysqlbackup
    state: touch
    mode: u+rwx,g+rx,a+rx
  changed_when: false
  tags:
    - automysqlbackup

- name: Create Post-Backup file
  copy:
    content: "{{ automysqlbackup_postbackup_content }}"
    dest: "{{ automysqlbackup_postbackup_file }}"
    owner: root
    group: root
    mode: u+rwx,g+rx,o+rx
  when: automysqlbackup_postbackup
  tags:
    - automysqlbackup

# Run configuration items
- include: configuration.yml

- name: Ensure deps installed for multicore archiving if enabled
  package:
    name: pigz
    state: present
  when: automysqlbackup_multicore == "yes" and automysqlbackup_compression == "gzip"
  tags:
    - automysqlbackup

- name: Ensure deps installed for multicore archiving if enabled
  package:
    name: pbzip2
    state: present
  when: automysqlbackup_multicore == "yes" and automysqlbackup_compression == "bzip2"
  tags:
    - automysqlbackup

- include: cron.yml
- include: cleanup.yml