---
- hosts: localhost
  become: yes
  vars_files:
  - secret.yml
  - vars.yml
  roles:
    - role: geerlingguy.mysql
    - role: geerlingguy.apache 
    - role: backup_and_automation
    - role: firewall
    - role: streama
    - role: ansible-nginx-revproxy