---
- hosts: localhost
  become: yes
  vars_files:
  - secret.yml
  - vars.yml
  roles:
    - role: geerlingguy.mysql
    - role: cloudflare_cdn
    - role: ansible-role-automysqlbackup
    - role: streama
    - role: hispanico.nginx-revproxy