---
- name: geerlingguy.mysql
  src: https://github.com/geerlingguy/ansible-role-mysql
  version: 3.1.0

- name: hispanico.nginx-revproxy
  src: https://github.com/hispanico/ansible-nginx-revproxy

- name: ansible-role-automysqlbackup
  src: https://github.com/guisea/ansible-role-automysqlbackup