---
- name: install mariadb role
  src: https://github.com/geerlingguy/ansible-role-mysql
  version: 3.1.0

- name: install nginx role
  src: https://github.com/hispanico/ansible-nginx-revproxy
  version: 1.3.0