---
- name: Install Java 8
  package:
    name: openjdk-8-jre
    state: present

- name: Remove old jar if exists
  file:
    path: /opt/streama.jar
    state: absent

- name: Copy the (custom) streama jar
  copy:
    src: tars/
    dest: /opt
    owner: root
    group: root
    mode: '0777'

- name: Untar the archives
  shell: cat /opt/streama.tar.gz.* | tar xzvf - -C /opt && cat /opt/frontend.tar.gz | tar xzvf - -C /var/www/html

- name: remove the archives
  shell: /bin/rm -rf /opt/streama.tar.gz.* && /bin/rm -rf /opt/frontend.tar.gz

- name: Set permissions for the jar
  file:
    path: /opt/streama.jar
    state: file
    owner: root
    group: root
    mode: '0777'

- name: Create streama service
  template:
    src: streama.j2
    dest: /etc/systemd/system/streama.service

- name: Copy streama configuration
  template:
    src: application.j2
    dest: /opt/application.yml

- name: Start and enable streama service
  service:
    name: streama
    state: started
    enabled: yes
